// All 58 Algerian wilayas — bilingual (EN / AR)
export const WILAYAS = [
  { code: '01', name_en: 'Adrar',             name_ar: 'أدرار' },
  { code: '02', name_en: 'Chlef',             name_ar: 'الشلف' },
  { code: '03', name_en: 'Laghouat',          name_ar: 'الأغواط' },
  { code: '04', name_en: 'Oum El Bouaghi',   name_ar: 'أم البواقي' },
  { code: '05', name_en: 'Batna',             name_ar: 'باتنة' },
  { code: '06', name_en: 'Béjaïa',            name_ar: 'بجاية' },
  { code: '07', name_en: 'Biskra',            name_ar: 'بسكرة' },
  { code: '08', name_en: 'Béchar',            name_ar: 'بشار' },
  { code: '09', name_en: 'Blida',             name_ar: 'البليدة' },
  { code: '10', name_en: 'Bouira',            name_ar: 'البويرة' },
  { code: '11', name_en: 'Tamanrasset',       name_ar: 'تمنراست' },
  { code: '12', name_en: 'Tébessa',           name_ar: 'تبسة' },
  { code: '13', name_en: 'Tlemcen',           name_ar: 'تلمسان' },
  { code: '14', name_en: 'Tiaret',            name_ar: 'تيارت' },
  { code: '15', name_en: 'Tizi Ouzou',        name_ar: 'تيزي وزو' },
  { code: '16', name_en: 'Algiers',           name_ar: 'الجزائر' },
  { code: '17', name_en: 'Djelfa',            name_ar: 'الجلفة' },
  { code: '18', name_en: 'Jijel',             name_ar: 'جيجل' },
  { code: '19', name_en: 'Sétif',             name_ar: 'سطيف' },
  { code: '20', name_en: 'Saïda',             name_ar: 'سعيدة' },
  { code: '21', name_en: 'Skikda',            name_ar: 'سكيكدة' },
  { code: '22', name_en: 'Sidi Bel Abbès',   name_ar: 'سيدي بلعباس' },
  { code: '23', name_en: 'Annaba',            name_ar: 'عنابة' },
  { code: '24', name_en: 'Guelma',            name_ar: 'قالمة' },
  { code: '25', name_en: 'Constantine',       name_ar: 'قسنطينة' },
  { code: '26', name_en: 'Médéa',             name_ar: 'المدية' },
  { code: '27', name_en: 'Mostaganem',        name_ar: 'مستغانم' },
  { code: '28', name_en: "M'Sila",            name_ar: 'المسيلة' },
  { code: '29', name_en: 'Mascara',           name_ar: 'معسكر' },
  { code: '30', name_en: 'Ouargla',           name_ar: 'ورقلة' },
  { code: '31', name_en: 'Oran',              name_ar: 'وهران' },
  { code: '32', name_en: 'El Bayadh',         name_ar: 'البيض' },
  { code: '33', name_en: 'Illizi',            name_ar: 'إليزي' },
  { code: '34', name_en: 'Bordj Bou Arréridj', name_ar: 'برج بوعريريج' },
  { code: '35', name_en: 'Boumerdès',         name_ar: 'بومرداس' },
  { code: '36', name_en: 'El Tarf',           name_ar: 'الطارف' },
  { code: '37', name_en: 'Tindouf',           name_ar: 'تندوف' },
  { code: '38', name_en: 'Tissemsilt',        name_ar: 'تيسمسيلت' },
  { code: '39', name_en: 'El Oued',           name_ar: 'الوادي' },
  { code: '40', name_en: 'Khenchela',         name_ar: 'خنشلة' },
  { code: '41', name_en: 'Souk Ahras',        name_ar: 'سوق أهراس' },
  { code: '42', name_en: 'Tipaza',            name_ar: 'تيبازة' },
  { code: '43', name_en: 'Mila',              name_ar: 'ميلة' },
  { code: '44', name_en: 'Aïn Defla',         name_ar: 'عين الدفلى' },
  { code: '45', name_en: 'Naâma',             name_ar: 'النعامة' },
  { code: '46', name_en: 'Aïn Témouchent',    name_ar: 'عين تموشنت' },
  { code: '47', name_en: 'Ghardaïa',          name_ar: 'غرداية' },
  { code: '48', name_en: 'Relizane',          name_ar: 'غليزان' },
  { code: '49', name_en: 'Timimoun',          name_ar: 'تيميمون' },
  { code: '50', name_en: 'Bordj Badji Mokhtar', name_ar: 'برج باجي مختار' },
  { code: '51', name_en: 'Ouled Djellal',     name_ar: 'أولاد جلال' },
  { code: '52', name_en: 'Béni Abbès',        name_ar: 'بني عباس' },
  { code: '53', name_en: 'In Salah',          name_ar: 'عين صالح' },
  { code: '54', name_en: 'In Guezzam',        name_ar: 'عين قزام' },
  { code: '55', name_en: 'Touggourt',         name_ar: 'تقرت' },
  { code: '56', name_en: 'Djanet',            name_ar: 'جانت' },
  { code: '57', name_en: "El M'Ghair",        name_ar: 'المغير' },
  { code: '58', name_en: 'El Meniaa',         name_ar: 'المنيعة' },
];
