// All 58 Algerian wilayas with their major communes
export const WILAYAS = [
  { code: '01', name: 'Adrar', communes: ['Adrar', 'Aoulef', 'Timimoun', 'Reggane', 'Zaouiet Kounta', 'Bordj Badji Mokhtar', 'Fenoughil'] },
  { code: '02', name: 'Chlef', communes: ['Chlef', 'Ténès', 'Abou El Hassan', 'El Karimia', 'Oued Fodda', 'Boukadir', 'Beni Haoua', 'Chettia'] },
  { code: '03', name: 'Laghouat', communes: ['Laghouat', 'Ksar El Hirane', 'Brida', 'Gueltat Sidi Saad', 'Aflou', 'Sidi Makhlouf', 'Hassi Rmel'] },
  { code: '04', name: 'Oum El Bouaghi', communes: ['Oum El Bouaghi', 'Aïn Beïda', 'Aïn M\'lila', 'Souk Naamane', 'Aïn Fakroun', 'Meskiana', 'Ksar Sbahi'] },
  { code: '05', name: 'Batna', communes: ['Batna', 'Aïn Touta', 'Barika', 'N\'gaous', 'Arris', 'Timgad', 'Merouana', 'Tazoult'] },
  { code: '06', name: 'Béjaïa', communes: ['Béjaïa', 'Akbou', 'Amizour', 'El Kseur', 'Kherrata', 'Sidi Aïch', 'Tazmalt', 'Tichy', 'Aokas'] },
  { code: '07', name: 'Biskra', communes: ['Biskra', 'Tolga', 'Ouled Djellal', 'Sidi Okba', 'El Outaya', 'Zeribet El Oued', 'M\'chounèche'] },
  { code: '08', name: 'Béchar', communes: ['Béchar', 'Abadla', 'Beni Abbès', 'Igli', 'Kenadsa', 'Lahmar', 'Taghit'] },
  { code: '09', name: 'Blida', communes: ['Blida', 'Boufarik', 'Meftah', 'Bougara', 'Larbaa', 'Bouinan', 'Chiffa', 'Ouled Yaïch', 'El Affroun'] },
  { code: '10', name: 'Bouira', communes: ['Bouira', 'Lakhdaria', 'Sour El Ghozlane', 'Ain Bessem', 'Mchedallah', 'Boukram', 'El Hachimia'] },
  { code: '11', name: 'Tamanrasset', communes: ['Tamanrasset', 'In Guezzam', 'In Salah', 'Abalessa', 'Tin Zaouatine', 'Ideles'] },
  { code: '12', name: 'Tébessa', communes: ['Tébessa', 'Cheria', 'Bir El Ater', 'El Aouinet', 'Ouenza', 'Morsott', 'El Ma Labiod'] },
  { code: '13', name: 'Tlemcen', communes: ['Tlemcen', 'Nedroma', 'Maghnia', 'Ghazaouet', 'Sébdou', 'Beni Snous', 'Remchi', 'Ouled Mimoun'] },
  { code: '14', name: 'Tiaret', communes: ['Tiaret', 'Frenda', 'Mahdia', 'Sougueur', 'Ksar Chellala', 'Rahouia', 'Ain Deheb'] },
  { code: '15', name: 'Tizi Ouzou', communes: ['Tizi Ouzou', 'Azazga', 'Boghni', 'Draa El Mizan', 'Tigzirt', 'Maatkas', 'Beni Douala', 'Larbaa Nait Irathen'] },
  { code: '16', name: 'Alger', communes: ['Alger Centre', 'Bab El Oued', 'Bab Ezzouar', 'Bir Mourad Raïs', 'Bordj El Kiffan', 'Cheraga', 'Dar El Beïda', 'Draria', 'El Biar', 'El Harrach', 'El Madania', 'Hydra', 'Hussein Dey', 'Kouba', 'Rouïba', 'Birkhadem', 'Sidi M\'Hamed', 'Ben Aknoun', 'Oued Smar', 'Reghaia'] },
  { code: '17', name: 'Djelfa', communes: ['Djelfa', 'Ain Oussera', 'Messaad', 'Birine', 'Charef', 'Selmana', 'El Idrissia', 'Hassi El Euch'] },
  { code: '18', name: 'Jijel', communes: ['Jijel', 'El Milia', 'Taher', 'Chekfa', 'Ziama Mansouriah', 'Djimla', 'Kaous'] },
  { code: '19', name: 'Sétif', communes: ['Sétif', 'Aïn Azel', 'El Eulma', 'Bougaa', 'Hammam Guergour', 'Kherrata', 'Salah Bey', 'Bordj Bou Arreridj'] },
  { code: '20', name: 'Saïda', communes: ['Saïda', 'Ain El Hadjar', 'Moulay Larbi', 'El Hassasna', 'Sidi Ahmed', 'Ouled Brahim'] },
  { code: '21', name: 'Skikda', communes: ['Skikda', 'El Harrouch', 'Azzaba', 'Collo', 'Ramdane Djamel', 'Tamalous', 'Ben Azzouz'] },
  { code: '22', name: 'Sidi Bel Abbès', communes: ['Sidi Bel Abbès', 'Aïn El Berd', 'Mascara', 'Teghalimet', 'Ben Badis', 'Moulay Slissen', 'Tessala'] },
  { code: '23', name: 'Annaba', communes: ['Annaba', 'El Bouni', 'El Hadjar', 'Seraïdi', 'Berrahal', 'Aïn Berda', 'Chetaïbi'] },
  { code: '24', name: 'Guelma', communes: ['Guelma', 'Bouchegouf', 'Héliopolis', 'Oued Zenati', 'Hammam Debagh', 'Medjez Amar'] },
  { code: '25', name: 'Constantine', communes: ['Constantine', 'El Khroub', 'Hamma Bouziane', 'Aïn Abid', 'Didouche Mourad', 'Zighoud Youcef', 'Ibn Ziad'] },
  { code: '26', name: 'Médéa', communes: ['Médéa', 'Berrouaghia', 'Ksar El Boukhari', 'Tablat', 'Ain Boucif', 'El Omaria', 'Si Mahdjoub'] },
  { code: '27', name: 'Mostaganem', communes: ['Mostaganem', 'Ain Tedles', 'Mesra', 'Kheir Eddine', 'Bouguirat', 'Hadjadj', 'Sidi Lakhdar'] },
  { code: '28', name: 'M\'Sila', communes: ['M\'Sila', 'Boussaada', 'Ain El Hadjel', 'Sidi Aissa', 'Beni Ilmane', 'El Houamed', 'Djezzar'] },
  { code: '29', name: 'Mascara', communes: ['Mascara', 'Sig', 'Mohammadia', 'Tighennif', 'Bouhanifia', 'Ain Fares', 'Matemore'] },
  { code: '30', name: 'Ouargla', communes: ['Ouargla', 'Hassi Messaoud', 'Touggourt', 'N\'Goussa', 'Sidi Slimane', 'Temacine', 'Ain Beida'] },
  { code: '31', name: 'Oran', communes: ['Oran', 'Aïn El Türck', 'Arzew', 'Bethioua', 'Es Sénia', 'Bir El Djir', 'Hassi Bounif', 'Oued Tlelat', 'Sidi Chahmi', 'Mers El Kebir'] },
  { code: '32', name: 'El Bayadh', communes: ['El Bayadh', 'Rogassa', 'Brezina', 'Chellala', 'Ain Sefra', 'El Abiodh Sidi Cheikh'] },
  { code: '33', name: 'Illizi', communes: ['Illizi', 'Djanet', 'In Aménas', 'Bordj Omar Driss', 'Debdeb'] },
  { code: '34', name: 'Bordj Bou Arreridj', communes: ['Bordj Bou Arreridj', 'Ras El Oued', 'Bir Kasdali', 'El Achir', 'Mansourah', 'Medjana', 'Colla'] },
  { code: '35', name: 'Boumerdès', communes: ['Boumerdès', 'Khemis El Khechna', 'Bordj Menaïel', 'Dellys', 'Boudouaou', 'Isser', 'Thenia', 'Si Mustapha'] },
  { code: '36', name: 'El Tarf', communes: ['El Tarf', 'Ben Mehidi', 'Drean', 'Besbes', 'Chihani', 'Bouteldja', 'Ain El Assel'] },
  { code: '37', name: 'Tindouf', communes: ['Tindouf', 'Oum El Assel'] },
  { code: '38', name: 'Tissemsilt', communes: ['Tissemsilt', 'Theniet El Had', 'Khemisti', 'Lardjem', 'Bordj Bou Naama', 'Beni Chaib'] },
  { code: '39', name: 'El Oued', communes: ['El Oued', 'Guemar', 'Robbah', 'Kouinine', 'Bayadha', 'Douar El Ma', 'Hassani Abdelkrim', 'Reguiba'] },
  { code: '40', name: 'Khenchela', communes: ['Khenchela', 'Ain Touila', 'Chechar', 'Tamza', 'Kais', 'Bouhmama', 'El Hamma'] },
  { code: '41', name: 'Souk Ahras', communes: ['Souk Ahras', 'Sedrata', 'Taoura', 'Mechroha', 'Oum El Adhaim', 'Bir Bouhouche'] },
  { code: '42', name: 'Tipaza', communes: ['Tipaza', 'Koléa', 'Cherchell', 'Hadjout', 'Bouismail', 'Marengo', 'Merad', 'Ain Tagourait'] },
  { code: '43', name: 'Mila', communes: ['Mila', 'Ferdjioua', 'Chelghoum Laid', 'Rouached', 'Grarem Gouga', 'Tassadane Haddada'] },
  { code: '44', name: 'Aïn Defla', communes: ['Aïn Defla', 'Miliana', 'Khemis Miliana', 'El Attaf', 'Ain Soltane', 'Djendel', 'Boumedfaa'] },
  { code: '45', name: 'Naâma', communes: ['Naâma', 'Mecheria', 'Ain Sefra', 'Sfissifa', 'Tiout', 'Moghrar', 'El Biod'] },
  { code: '46', name: 'Aïn Témouchent', communes: ['Aïn Témouchent', 'Hammam Bou Hadjar', 'Beni Saf', 'El Amria', 'Aghlal', 'Oulhassa Gheraba', 'Hassi El Ghella'] },
  { code: '47', name: 'Ghardaïa', communes: ['Ghardaïa', 'Guerrara', 'Metlili', 'El Meniaa', 'Berriane', 'Dhayet Bendhahoua', 'Bounoura'] },
  { code: '48', name: 'Relizane', communes: ['Relizane', 'Mazouna', 'Sidi M\'Hamed Ben Ali', 'El Hamadna', 'Oued Rhiou', 'Ain Tarek', 'Mendès'] },
  { code: '49', name: 'El M\'Ghair', communes: ['El M\'Ghair', 'Djamaa', 'Sidi Khaled', 'Meghaïer', 'Oued Allenda', 'Sidi Amrane'] },
  { code: '50', name: 'El Meniaa', communes: ['El Meniaa', 'Hassi Gara', 'In Salah', 'Foggaret Ezzaouia'] },
  { code: '51', name: 'Ouled Djellal', communes: ['Ouled Djellal', 'Doucen', 'Ras El Miad', 'Sidi Khaled'] },
  { code: '52', name: 'Bordj Baji Mokhtar', communes: ['Bordj Baji Mokhtar', 'Timiaouine'] },
  { code: '53', name: 'Béni Abbès', communes: ['Béni Abbès', 'Béchar', 'Tamtert', 'Ougarta'] },
  { code: '54', name: 'Timimoun', communes: ['Timimoun', 'Aougrout', 'Charouine', 'Deldoul', 'Ksar Kaddour'] },
  { code: '55', name: 'Touggourt', communes: ['Touggourt', 'Temacine', 'Tebesbest', 'Nezla', 'M\'naguer'] },
  { code: '56', name: 'Djanet', communes: ['Djanet', 'Bordj El Haouasse', 'In Amguel'] },
  { code: '57', name: 'In Salah', communes: ['In Salah', 'Foggaret Ezzaouia', 'In Ghar'] },
  { code: '58', name: 'In Guezzam', communes: ['In Guezzam', 'Tin Zaouatine'] },
];

export const WILAYA_NAMES = WILAYAS.map(w => w.name);

export function getCommunesByWilaya(wilayaName) {
  return WILAYAS.find(w => w.name === wilayaName)?.communes || [];
}
